# A plugin for PocketMine-MP that will show an UI for information and guides when players joins the server.
# Copyright (C) 2020-2022 Kygekraqmak, KygekTeam
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: KygekJoinUI
main: Kygekraqmak\KygekJoinUI\Main
api: 4.0.0
version: 2.1.0
authors: [Kygekraqmak, KygekTeam]
description: Shows an UI for information and guides of the server when players joins the server
website: https://github.com/thebigcrafter/KygekJoinUI